title: Aryan Raj
email: araj7@wisc.edu
description: >-
  Data Scientist | AI Explorer | Blogger.
baseurl: ""  
url: "https://aryn920.github.io"
theme: minima

author:
  name: Aryan Raj
  email: araj7@wisc.edu

social_links:
  linkedin: https://www.linkedin.com/in/aryan-raj-a742bb203
  github: https://github.com/aryn920
